
export const headCells1 = [
    { id: 'branchCode', label: "كود الفرع"},
    { id: 'branchName', label: "اسم الفرع" },
    { id: 'nameOfPlannedVisitor', label: " اسم الجهة او الشخص الزمع زيارته" },
    { id: 'clientType',  label: "نوع العميل " },
    { id: 'current',  label: "حالي" },
    { id: 'currentdeterminedDate',  label: "تاريخ تحديد الزيارة"},
    { id: 'ofKnowing',  label:' بمعرفة' },
    { id: 'determinedDateType',  label: "الصفة" },
    { id: 'visitDate',  label:  "ميعاد الزيارة" },
    { id: 'visitPlace',  label: "مكان الزيارة" },
    { id: 'nameOfVisitor',  label: " اسم القائم بالزيارة" },
    { id: 'nameOfVisitorType',  label: "الصفة"},
    { id: 'constantVisitDate',  label:  "تاريخ الزيارة" },
    { id: 'personToBeInterviewed',  label: " الشخص المسئول المراد مقابلته" },
    { id: 'personToBeInterviewedType',  label: "الصفة" },
    { id: 'personToBeInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewed',  label: "اشخاص مسئولين اخرين" },
    { id: 'anotherPersonToInterviewedType',  label: "الصفة"},
    { id: 'anotherPersonToInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewedOne',  label: "اشخاص مسئولين اخرين"},
    { id:'anotherPersonToInterviewedOneType',  label: "الصفة" },
    { id: 'anotherPersonToInterviewedOnePhoneNum',  label:  "هاتف "},
    { id: 'reasonOfVisit',  label: "  الغرض من الزيارة" },
    { id: 'visitResult',  label:  "نتيجة الزيارة"},
    { id: 'anotherExtraResults',  label:  "نتائج اخري اضافية" },
    { id: 'marketingManagerSign',  label:  " توقيع مدير المبيعات"},
    { id: 'branchManagerSign',  label: " توقيع مدير الفرع" },
    { id: 'notes',  label: "الملاحظات" },
    ];

export const headCells2 = [
    { id: 'branchName', label: "اسم الفرع" },
    { id: 'branchCode', label: "كود الفرع"},
    { id: 'nameOfPlannedVisitor', label: " اسم الجهة او الشخص الزمع زيارته" },
    { id: 'clientType',  label: "نوع العميل " },
    { id: 'current',  label: "حالي" },
    { id: 'currentdeterminedDate',  label: "تاريخ تحديد الزيارة"},
    { id: 'ofKnowing',  label:' بمعرفة' },
    { id: 'determinedDateType',  label: "الصفة" },
    { id: 'visitDate',  label:  "ميعاد الزيارة" },
    { id: 'visitPlace',  label: "مكان الزيارة" },
    { id: 'nameOfVisitor',  label: " اسم القائم بالزيارة" },
    { id: 'nameOfVisitorType',  label: "الصفة"},
    { id: 'constantVisitDate',  label:  "تاريخ الزيارة" },
    { id: 'personToBeInterviewed',  label: " الشخص المسئول المراد مقابلته" },
    { id: 'personToBeInterviewedType',  label: "الصفة" },
    { id: 'personToBeInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewed',  label: "اشخاص مسئولين اخرين" },
    { id: 'anotherPersonToInterviewedType',  label: "الصفة"},
    { id: 'anotherPersonToInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewedOne',  label: "اشخاص مسئولين اخرين"},
    { id:'anotherPersonToInterviewedOneType',  label: "الصفة" },
    { id: 'anotherPersonToInterviewedOnePhoneNum',  label:  "هاتف "},
    { id: 'reasonOfVisit',  label: "  الغرض من الزيارة" },
    { id: 'visitResult',  label:  "نتيجة الزيارة"},
    { id: 'anotherExtraResults',  label:  "نتائج اخري اضافية" },
    { id: 'marketingManagerSign',  label:  " توقيع مدير المبيعات"},
    { id: 'branchManagerSign',  label: " توقيع مدير الفرع" },
    { id: 'notes',  label: "الملاحظات" },
    ];

    export const headCells3 = [
    { id: 'nameOfVisitor',  label: " اسم القائم بالزيارة" },
    { id: 'branchName', label: "اسم الفرع" },
    { id: 'branchCode', label: "كود الفرع"},
    { id: 'nameOfPlannedVisitor', label: " اسم الجهة او الشخص الزمع زيارته" },
    { id: 'clientType',  label: "نوع العميل " },
    { id: 'current',  label: "حالي" },
    { id: 'currentdeterminedDate',  label: "تاريخ تحديد الزيارة"},
    { id: 'ofKnowing',  label:' بمعرفة' },
    { id: 'determinedDateType',  label: "الصفة" },
    { id: 'visitDate',  label:  "ميعاد الزيارة" },
    { id: 'visitPlace',  label: "مكان الزيارة" },
    { id: 'nameOfVisitorType',  label: "الصفة"},
    { id: 'constantVisitDate',  label:  "تاريخ الزيارة" },
    { id: 'personToBeInterviewed',  label: " الشخص المسئول المراد مقابلته" },
    { id: 'personToBeInterviewedType',  label: "الصفة" },
    { id: 'personToBeInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewed',  label: "اشخاص مسئولين اخرين" },
    { id: 'anotherPersonToInterviewedType',  label: "الصفة"},
    { id: 'anotherPersonToInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewedOne',  label: "اشخاص مسئولين اخرين"},
    { id:'anotherPersonToInterviewedOneType',  label: "الصفة" },
    { id: 'anotherPersonToInterviewedOnePhoneNum',  label:  "هاتف "},
    { id: 'reasonOfVisit',  label: "  الغرض من الزيارة" },
    { id: 'visitResult',  label:  "نتيجة الزيارة"},
    { id: 'anotherExtraResults',  label:  "نتائج اخري اضافية" },
    { id: 'marketingManagerSign',  label:  " توقيع مدير المبيعات"},
    { id: 'branchManagerSign',  label: " توقيع مدير الفرع" },
    { id: 'notes',  label: "الملاحظات" },
    ];

    export const headCells4 = [
    { id: 'personToBeInterviewed',  label: " الشخص المسئول المراد مقابلته" },
    { id: 'branchName', label: "اسم الفرع" },
    { id: 'branchCode', label: "كود الفرع"},
    { id: 'nameOfPlannedVisitor', label: " اسم الجهة او الشخص الزمع زيارته" },
    { id: 'clientType',  label: "نوع العميل " },
    { id: 'current',  label: "حالي" },
    { id: 'currentdeterminedDate',  label: "تاريخ تحديد الزيارة"},
    { id: 'ofKnowing',  label:' بمعرفة' },
    { id: 'determinedDateType',  label: "الصفة" },
    { id: 'visitDate',  label:  "ميعاد الزيارة" },
    { id: 'visitPlace',  label: "مكان الزيارة" },
    { id: 'nameOfVisitor',  label: " اسم القائم بالزيارة" },
    { id: 'nameOfVisitorType',  label: "الصفة"},
    { id: 'constantVisitDate',  label:  "تاريخ الزيارة" },
    { id: 'personToBeInterviewedType',  label: "الصفة" },
    { id: 'personToBeInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewed',  label: "اشخاص مسئولين اخرين" },
    { id: 'anotherPersonToInterviewedType',  label: "الصفة"},
    { id: 'anotherPersonToInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewedOne',  label: "اشخاص مسئولين اخرين"},
    { id:'anotherPersonToInterviewedOneType',  label: "الصفة" },
    { id: 'anotherPersonToInterviewedOnePhoneNum',  label:  "هاتف "},
    { id: 'reasonOfVisit',  label: "  الغرض من الزيارة" },
    { id: 'visitResult',  label:  "نتيجة الزيارة"},
    { id: 'anotherExtraResults',  label:  "نتائج اخري اضافية" },
    { id: 'marketingManagerSign',  label:  " توقيع مدير المبيعات"},
    { id: 'branchManagerSign',  label: " توقيع مدير الفرع" },
    { id: 'notes',  label: "الملاحظات" },
    ];

    export const headCells5 = [
    { id: 'personToBeInterviewedType',  label: "الصفة" },
    { id: 'branchName', label: "اسم الفرع" },
    { id: 'branchCode', label: "كود الفرع"},
    { id: 'nameOfPlannedVisitor', label: " اسم الجهة او الشخص الزمع زيارته" },
    { id: 'clientType',  label: "نوع العميل " },
    { id: 'current',  label: "حالي" },
    { id: 'currentdeterminedDate',  label: "تاريخ تحديد الزيارة"},
    { id: 'ofKnowing',  label:' بمعرفة' },
    { id: 'determinedDateType',  label: "الصفة" },
    { id: 'visitDate',  label:  "ميعاد الزيارة" },
    { id: 'visitPlace',  label: "مكان الزيارة" },
    { id: 'nameOfVisitor',  label: " اسم القائم بالزيارة" },
    { id: 'nameOfVisitorType',  label: "الصفة"},
    { id: 'constantVisitDate',  label:  "تاريخ الزيارة" },
    { id: 'personToBeInterviewed',  label: " الشخص المسئول المراد مقابلته" },
    { id: 'personToBeInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewed',  label: "اشخاص مسئولين اخرين" },
    { id: 'anotherPersonToInterviewedType',  label: "الصفة"},
    { id: 'anotherPersonToInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewedOne',  label: "اشخاص مسئولين اخرين"},
    { id:'anotherPersonToInterviewedOneType',  label: "الصفة" },
    { id: 'anotherPersonToInterviewedOnePhoneNum',  label:  "هاتف "},
    { id: 'reasonOfVisit',  label: "  الغرض من الزيارة" },
    { id: 'visitResult',  label:  "نتيجة الزيارة"},
    { id: 'anotherExtraResults',  label:  "نتائج اخري اضافية" },
    { id: 'marketingManagerSign',  label:  " توقيع مدير المبيعات"},
    { id: 'branchManagerSign',  label: " توقيع مدير الفرع" },
    { id: 'notes',  label: "الملاحظات" },
    ];

    export const headCells6 = [
    { id: 'personToBeInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'branchName', label: "اسم الفرع" },
    { id: 'branchCode', label: "كود الفرع"},
    { id: 'nameOfPlannedVisitor', label: " اسم الجهة او الشخص الزمع زيارته" },
    { id: 'clientType',  label: "نوع العميل " },
    { id: 'current',  label: "حالي" },
    { id: 'currentdeterminedDate',  label: "تاريخ تحديد الزيارة"},
    { id: 'ofKnowing',  label:' بمعرفة' },
    { id: 'determinedDateType',  label: "الصفة" },
    { id: 'visitDate',  label:  "ميعاد الزيارة" },
    { id: 'visitPlace',  label: "مكان الزيارة" },
    { id: 'nameOfVisitor',  label: " اسم القائم بالزيارة" },
    { id: 'nameOfVisitorType',  label: "الصفة"},
    { id: 'constantVisitDate',  label:  "تاريخ الزيارة" },
    { id: 'personToBeInterviewed',  label: " الشخص المسئول المراد مقابلته" },
    { id: 'personToBeInterviewedType',  label: "الصفة" },
    { id: 'anotherPersonToInterviewed',  label: "اشخاص مسئولين اخرين" },
    { id: 'anotherPersonToInterviewedType',  label: "الصفة"},
    { id: 'anotherPersonToInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewedOne',  label: "اشخاص مسئولين اخرين"},
    { id:'anotherPersonToInterviewedOneType',  label: "الصفة" },
    { id: 'anotherPersonToInterviewedOnePhoneNum',  label:  "هاتف "},
    { id: 'reasonOfVisit',  label: "  الغرض من الزيارة" },
    { id: 'visitResult',  label:  "نتيجة الزيارة"},
    { id: 'anotherExtraResults',  label:  "نتائج اخري اضافية" },
    { id: 'marketingManagerSign',  label:  " توقيع مدير المبيعات"},
    { id: 'branchManagerSign',  label: " توقيع مدير الفرع" },
    { id: 'notes',  label: "الملاحظات" },
    ];

    export const headCells7 = [
    { id: 'visitResult',  label:  "نتيجة الزيارة"},
    { id: 'branchName', label: "اسم الفرع" },
    { id: 'branchCode', label: "كود الفرع"},
    { id: 'nameOfPlannedVisitor', label: " اسم الجهة او الشخص الزمع زيارته" },
    { id: 'clientType',  label: "نوع العميل " },
    { id: 'current',  label: "حالي" },
    { id: 'currentdeterminedDate',  label: "تاريخ تحديد الزيارة"},
    { id: 'ofKnowing',  label:' بمعرفة' },
    { id: 'determinedDateType',  label: "الصفة" },
    { id: 'visitDate',  label:  "ميعاد الزيارة" },
    { id: 'visitPlace',  label: "مكان الزيارة" },
    { id: 'nameOfVisitor',  label: " اسم القائم بالزيارة" },
    { id: 'nameOfVisitorType',  label: "الصفة"},
    { id: 'constantVisitDate',  label:  "تاريخ الزيارة" },
    { id: 'personToBeInterviewed',  label: " الشخص المسئول المراد مقابلته" },
    { id: 'personToBeInterviewedType',  label: "الصفة" },
    { id: 'personToBeInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewed',  label: "اشخاص مسئولين اخرين" },
    { id: 'anotherPersonToInterviewedType',  label: "الصفة"},
    { id: 'anotherPersonToInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewedOne',  label: "اشخاص مسئولين اخرين"},
    { id:'anotherPersonToInterviewedOneType',  label: "الصفة" },
    { id: 'anotherPersonToInterviewedOnePhoneNum',  label:  "هاتف "},
    { id: 'reasonOfVisit',  label: "  الغرض من الزيارة" },
    { id: 'anotherExtraResults',  label:  "نتائج اخري اضافية" },
    { id: 'marketingManagerSign',  label:  " توقيع مدير المبيعات"},
    { id: 'branchManagerSign',  label: " توقيع مدير الفرع" },
    { id: 'notes',  label: "الملاحظات" },
    ];

    export const headCells8 = [
    { id: 'constantVisitDate',  label:  "تاريخ الزيارة" },
    { id: 'branchName', label: "اسم الفرع" },
    { id: 'branchCode', label: "كود الفرع"},
    { id: 'nameOfPlannedVisitor', label: " اسم الجهة او الشخص الزمع زيارته" },
    { id: 'clientType',  label: "نوع العميل " },
    { id: 'current',  label: "حالي" },
    { id: 'currentdeterminedDate',  label: "تاريخ تحديد الزيارة"},
    { id: 'ofKnowing',  label:' بمعرفة' },
    { id: 'determinedDateType',  label: "الصفة" },
    { id: 'visitDate',  label:  "ميعاد الزيارة" },
    { id: 'visitPlace',  label: "مكان الزيارة" },
    { id: 'nameOfVisitor',  label: " اسم القائم بالزيارة" },
    { id: 'nameOfVisitorType',  label: "الصفة"},
    { id: 'personToBeInterviewed',  label: " الشخص المسئول المراد مقابلته" },
    { id: 'personToBeInterviewedType',  label: "الصفة" },
    { id: 'personToBeInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewed',  label: "اشخاص مسئولين اخرين" },
    { id: 'anotherPersonToInterviewedType',  label: "الصفة"},
    { id: 'anotherPersonToInterviewedPhoneNum',  label:  "هاتف " },
    { id: 'anotherPersonToInterviewedOne',  label: "اشخاص مسئولين اخرين"},
    { id:'anotherPersonToInterviewedOneType',  label: "الصفة" },
    { id: 'anotherPersonToInterviewedOnePhoneNum',  label:  "هاتف "},
    { id: 'reasonOfVisit',  label: "  الغرض من الزيارة" },
    { id: 'visitResult',  label:  "نتيجة الزيارة"},
    { id: 'anotherExtraResults',  label:  "نتائج اخري اضافية" },
    { id: 'marketingManagerSign',  label:  " توقيع مدير المبيعات"},
    { id: 'branchManagerSign',  label: " توقيع مدير الفرع" },
    { id: 'notes',  label: "الملاحظات" },
    ];